# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1551ca3abc08e3c2248ddd734bc14132829d5c75371e36a1404952a8d1f1ada8cbd69912f844f91d334002b7151ffb98a6b1ac66891e3d31f39049169b264878

test:
  secret_key_base: 357fcd948b52864584867e9d0db9f826d2918123ac97d8a3f0d9c3880737178c623858358f0776ef1a15aec5a58053cb2ace40d0629173e2fa2bd75ba8568ac8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
